# Generated by Django 3.1.6 on 2021-02-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=12, unique=True, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
